package com.dvelop.smartnotes.domino.directory;

import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import lotus.domino.Database;
import lotus.domino.Document;
import lotus.domino.NotesException;
import lotus.domino.Session;

import com.dvelop.smartnotes.domino.resources.Constants;

public class GroupBuilder {

    private static final String GROUP_TYPE_MULTI_PURPOSE = "0";
    private static final String FIELD_COMMENTS = "Comments";
    private static final String FIELD_DESCRIPTION = "ListDescription";
    private static final String FIELD_CATEGORY = "ListCategory";
    private static final String FIELD_GROUP_TYPE = "GroupType";
    private static final String FIELD_MEMBERS = "Members";
    private static final String FIELD_GROUP_NAME = "ListName";
    private static final String GROUP_FORM = "Group";
    private Session session;
    private Database addressbook;
    private Document groupDoc;

    public GroupBuilder(Session session, Database addressbook) {
	this.session = session;
	this.addressbook = addressbook;
    }

    public void createGroup(String groupName) {
	createGroup(groupName, new ArrayList<String>());
    }

    public void createGroup(String groupName, List<String> members) {
	Vector<String> membersVector = new Vector<String>(members);
	createGroup(groupName, membersVector);
    }

    public void createGroup(String groupName, Vector<String> members) {
	try {
	    groupDoc = addressbook.createDocument();
	    groupDoc.replaceItemValue(Constants.ITEM_FORM, GROUP_FORM);
	    groupDoc.replaceItemValue(FIELD_GROUP_NAME, groupName);
	    groupDoc.replaceItemValue(FIELD_MEMBERS, members);
	    groupDoc.replaceItemValue(FIELD_GROUP_TYPE, GROUP_TYPE_MULTI_PURPOSE);
	    groupDoc.replaceItemValue(FIELD_CATEGORY, "d.3ecm");
	    groupDoc.replaceItemValue(FIELD_DESCRIPTION, "Group for Users who should use d.3ecm Widget");
	    groupDoc.replaceItemValue(
		    FIELD_COMMENTS,
		    "***************************************\n* Autogenerated Group for d.3ecm. *\n***********************************\n\nPlease add the users and/or groups, who should get d.3ecm funtionality in their IBM Notes Clients");
	    groupDoc.computeWithForm(false, true);
	    groupDoc.save(true, false, false);
	} catch (NotesException e) {
	    e.printStackTrace();
	} finally {

	}
    }

    public void appendGroupToMasterPolicy(Document masterPolicy) {
	try {
	    masterPolicy.replaceItemValue("AssignedUsrGrpNames", groupDoc.getItemValueString(FIELD_GROUP_NAME));
	    masterPolicy.save(true, false, false);
	} catch (NotesException e) {
	    e.printStackTrace();
	}

    }

    public void createGroup(String groupName, String member) {
	Vector<String> membersVector = new Vector<String>();
	membersVector.add(member);
	createGroup(groupName, membersVector);
    }

    public void addMember(String member) {
	try {
	    Vector<String> members = groupDoc.getItemValue(FIELD_MEMBERS);
	    members.add(member);
	    groupDoc.replaceItemValue(FIELD_MEMBERS, members);
	    groupDoc.save(true, false, false);
	} catch (NotesException e) {
	    e.printStackTrace();
	}

    }
}
